# Avaliação de Modelos - Métricas de Regressão

Quando queremos avaliar um aluno no ENEM, por exemplo, comparamos o gabarito oficial do ENEM com o gabarito do aluno. De forma semelhante avaliamos os algoritmos de aprendizado supervisionado, ou seja, comparando o label verdadeiro (y_true) com o label estimado/predito pelo algoritmo (y_pred).

In [1]:
import numpy as np
from sklearn import datasets
from sklearn import metrics
from sklearn import model_selection
from sklearn import linear_model

### Carregue o dataset de diabetes

O label é uma medida quantitativa da progressão da doença um ano após os dados iniciais (features).

In [2]:
X, y = datasets.load_diabetes(return_X_y=True)

In [3]:
X.shape, y.shape

((442, 10), (442,))

In [4]:
y[:5]

array([151.,  75., 141., 206., 135.])

### Divida o dataset em 75% para treino e 25% para teste.

In [5]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, random_state=42)

### Crie um y_test_mean contendo a média de y_test em todos os seus valores

In [22]:
y_train_mean = np.full(y_test.shape, np.mean(y_train))

### Mostre os primeiros 5 elementos de y_test_mean

In [23]:
print(y_train_mean[:5])

[154.34441088 154.34441088 154.34441088 154.34441088 154.34441088]


### Crie um y_train_max contendo o maior valor de y_train em todos os seus valores

In [24]:
y_train_max = np.full(y_test.shape, np.max(y_train))

### Treine o modelo usando o conjunto de dados de treino e o algoritmo de regressão linear

In [25]:
model_lr = linear_model.LinearRegression()

In [26]:
model_lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [1]:
import joblib

In [45]:
joblib.dump(model_lr, 'modelo_lr.dump')

['modelo_lr.dump']

In [27]:
model_lr.intercept_

151.66516982689936

In [28]:
model_lr.coef_

array([  47.74657117, -241.99180361,  531.96856896,  381.56529922,
       -918.49020552,  508.25147385,  116.94040498,  269.48508571,
        695.8062205 ,   26.32343144])

In [29]:
model_lr.predict([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

array([10794.60667249])

### Use o modelo treinado para realizar predições sobre o conjunto de teste

In [30]:
y_pred = model_lr.predict(X_test)

## Métrica MAE - Mean Absolute Error

$$ MAE = \frac{1}{n} \sum_{i=0}^{n-1}{ \vert y_i - \hat{y}_i \vert } $$

### Calcule o MAE comparando y_test com y_pred de forma manual, usando apenas os recursos do numpy

### Calcule o MAE comparando y_test com y_pred usando a métrica mean_absolute_error do scikit.

In [32]:
metrics.mean_absolute_error(y_test, y_pred)

41.548363283252066

### Calcule o MAE comparando o valor do conjunto de teste (y_test) com: valor predito (y_pred), valor do label (y_test), valor da média (y_test_mean) e valor máximo (y_test_max).

In [33]:
metrics.mean_absolute_error(y_test, y_pred)

41.548363283252066

In [34]:
metrics.mean_absolute_error(y_test, y_test)

0.0

In [35]:
metrics.mean_absolute_error(y_test, y_train_mean)

65.52742168150024

In [36]:
metrics.mean_absolute_error(y_test, y_train_max)

200.45945945945945

### Implemente a métrica MAE

41.548363283252066

In [39]:
from mylibs import metricas

In [40]:
metricas.mae(y_test, y_pred)

41.548363283252066

### Use sua implementação para calcular MAE comparando o valor do conjunto de teste (y_test) com o valor predito (y_pred)

## Métrica MSE - Mean Squared Error

$$ MSE = \frac{1}{n} \sum_{i=0}^{n-1}{ (y_i - \hat{y_i})^2 } $$

### Calcule o MSE comparando o valor do conjunto de teste (y_test) com: valor predito (y_pred), valor do label (y_test), valor da média (y_train_mean) e valor máximo (y_train_max).

In [46]:
metrics.mean_squared_error(y_test, y_pred)

2848.2953079329427

In [47]:
metrics.mean_squared_error(y_test, y_test)

0.0

In [48]:
metrics.mean_squared_error(y_test, y_train_mean)

5607.197930791938

In [49]:
metrics.mean_squared_error(y_test, y_train_max)

45713.68468468468

### Implemente o MSE

### Use sua implementação para calcular MSE comparando o valor do conjunto de teste (y_test) com o valor predito (y_pred)

## Métrica RMSE - Root Mean Squared Error

$$ RMSE = \sqrt{ MSE } $$

### Calcule o RMSE comparando o valor do conjunto de teste (y_test) com: valor predito (y_pred), valor do label (y_test), valor da média (y_test_mean) e valor máximo (y_test_max).

In [50]:
metrics.mean_squared_error(y_test, y_pred) ** 0.5

53.36942296795931

In [51]:
metrics.mean_squared_error(y_test, y_pred) ** (1/2)

53.36942296795931

In [57]:
np.std(y_test), np.mean(y_test)

(74.36188403951323, 145.54054054054055)

In [52]:
np.sqrt(metrics.mean_squared_error(y_test, y_pred))

53.36942296795931

In [53]:
metrics.mean_squared_error(y_test, y_test) ** 0.5

0.0

In [55]:
metrics.mean_squared_error(y_test, y_train_mean) ** 0.5

74.88122548938378

In [56]:
metrics.mean_squared_error(y_test, y_train_max) ** 0.5

213.8075879960407

### Implemente o RMSE

### Use sua implementação para calcular RMSE comparando o valor do conjunto de teste (y_test) com o valor predito (y_pred)

## Métrica MSLE - Mean squared logarithmic error

Usando quando não queremos que grandes erros sejam significativamente mais penalizados do que os pequenos, nos casos em que há valores com ordens de grandeza diferentes no rótulo.

Exemplo: Você deseja prever os preços futuros do imóvel e seu conjunto de dados inclui residências com ordens de magnitude diferentes no preço.

$$ MSLE = \frac{1}{n} \sum_{i=0}^{n-1} { ( \log{(y_i + 1)} - \log{(\hat{y}_i + 1)} )^2 } $$

### Calcule o MSE comparando o valor do conjunto de teste (y_test) com: valor predito (y_pred), valor do label (y_test), valor da média (y_test_mean) e valor máximo (y_test_max).

In [58]:
metrics.mean_squared_log_error(y_test, y_pred)

0.17473101967410773

In [59]:
metrics.mean_squared_log_error(y_test, y_test)

0.0

In [60]:
metrics.mean_squared_log_error(y_test, y_test)

0.0

In [61]:
metrics.mean_squared_log_error(y_test, y_train_mean)

0.3262411099085772

In [62]:
metrics.mean_squared_log_error(y_test, y_train_max)

1.2863896507131534

### Implemente o MSLE

In [64]:
msle(y_test, y_pred)

0.17473101967410773

In [76]:
metricas.mae(y_test, y_pred)

41.548363283252066

In [71]:
metricas.msle(y_test, y_pred)

0.17473101967410773

### Use sua implementação para calcular o MSLE comparando o valor do conjunto de teste (y_test) com o valor predito (y_pred)

## Métrica RMSLE - Root Mean squared logarithmic error

$$ RMSLE = \sqrt{ MSLE } $$

### Calcule o RMSLE comparando o valor do conjunto de teste (y_test) com: valor predito (y_pred), valor do label (y_test), valor da média (y_test_mean) e valor máximo (y_test_max).

In [ ]:
metrics.mean_squared_log_error(y_test, y_pred) ** 0.5

In [ ]:
metrics.mean_squared_log_error(y_test, y_test) ** 0.5

In [ ]:
metrics.mean_squared_log_error(y_test, y_test_mean) ** 0.5

In [ ]:
metrics.mean_squared_log_error(y_test, y_test_max) ** 0.5

### Implemente o RMSLE

### Use sua implementação para calcular o RMSLE comparando o valor do conjunto de teste (y_test) com o valor predito (y_pred)

## Métrica $R^2$ - Coeficiente de Determinação

### Avalie o modelo usando o conjunto de dados de teste e a métrica padrão

In [77]:
model_lr.score(X_test, y_test)

0.4849086635905802

### Que resultado é esse?

É o resultado da avaliação do modelo usando a métrica $R^2$, que também é chamada de coeficiente de determinação.

### Calcule $R^2$ comparando o valor do conjunto de teste (y_test) com: valor predito (y_pred), valor do label (y_test), valor da média (y_test_mean) e valor máximo (y_test_max).

In [78]:
metrics.r2_score(y_test, y_pred)

0.48490866359058016

In [82]:
metrics.r2_score(y_test, y_test)

1.0

In [83]:
metrics.r2_score(y_test, y_train_mean)

-0.014016723490579253

In [84]:
metrics.r2_score(y_test, y_train_max)

-7.266952822922468

### Cálculo do coeficiente de determinação ($R^2$) 

$$ R^2 = 1 - \frac{SS_{res}}{SS_{tot}} $$

$SS_{res}$ é a soma dos quadrados residuais:

$$ SS_{res} = \sum_{i}{ (y_i - \hat{y_i})^2 } $$

$SS_{tot}$ é a soma total dos quadrados da diferença em relação à média dos valores observados:

$$ SS_{tot} = \sum_{i}{ (y_i - \bar{y})^2 } $$


O melhor score possível é 1.0. Ele pode ser negativo em modelos muito ruins. 

Um modelo constante que sempre prediz o valor esperado de y, independente das features de entrada, obteria um score de 0.0.

### Implemente $R^2$

### Use sua implementação para calcular $R^2$ comparando o valor do conjunto de teste (y_test) com o valor predito (y_pred)